# Generated by Django 5.0.6 on 2024-05-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('discord_id', models.CharField(max_length=100, null=True, verbose_name='Discord ID')),
                ('event_used', models.BigIntegerField(default=0, null=True, verbose_name='Command used')),
                ('last_used_on', models.DateField(auto_now=True, null=True, verbose_name='Last Used On')),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TodayLuck',
            fields=[
                ('uid', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='uid')),
                ('location', models.CharField(max_length=100, null=True, verbose_name='Lucky Location')),
                ('container', models.CharField(max_length=100, null=True, verbose_name='Lucky Container')),
                ('weapon', models.CharField(max_length=100, null=True, verbose_name='Lucky Weapon')),
                ('item', models.CharField(max_length=100, null=True, verbose_name='Lucky Item')),
                ('summary', models.CharField(max_length=300, null=True, verbose_name='Summary')),
            ],
            options={
                'db_table': 'today_luck',
                'managed': False,
            },
        ),
    ]
