# Generated by Django 5.0.6 on 2024-05-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('uid', models.BigIntegerField(null=True, verbose_name='uid')),
                ('storage', models.CharField(max_length=100, null=True, verbose_name='storage')),
                ('letter_event', models.CharField(max_length=25, null=True, verbose_name='letter event')),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
    ]
