# Generated by Django 5.0.6 on 2024-05-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_events_delete_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('uid', models.BigIntegerField(null=True, verbose_name='uid')),
                ('achievement', models.CharField(max_length=300, null=True, verbose_name='Achievement')),
                ('storage', models.CharField(max_length=400, null=True, verbose_name='Storage')),
                ('koens', models.IntegerField(null=True, verbose_name='Koens')),
                ('status', models.CharField(default='not_claimed', max_length=20, null=True, verbose_name='Status')),
            ],
            options={
                'db_table': 'inventory',
                'managed': False,
            },
        ),
    ]
