# Generated by Django 5.0.6 on 2024-07-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalized_test_answer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('user_id', models.BigIntegerField(verbose_name='uid')),
                ('question_id', models.BigIntegerField(verbose_name='question id')),
                ('answers', models.CharField(max_length=224, null=True, verbose_name='answers')),
                ('time', models.DateTimeField(null=True, verbose_name='time')),
            ],
            options={
                'db_table': 'personalized_test_answer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personalized_test_question',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=225, null=True, verbose_name='title')),
                ('description', models.CharField(max_length=400, null=True, verbose_name='description')),
                ('image', models.URLField(null=True, verbose_name='image')),
                ('type', models.CharField(max_length=100, null=True, verbose_name='type')),
                ('time', models.DateTimeField(null=True, verbose_name='time')),
            ],
            options={
                'db_table': 'personalized_test_question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('sn', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='serial number')),
                ('date', models.DateField(null=True, verbose_name='date')),
                ('number_of_uses', models.IntegerField(default=0, null=True, verbose_name='number of uses')),
            ],
            options={
                'db_table': 'record',
                'managed': False,
            },
        ),
    ]
