# Generated by Django 5.0.6 on 2024-07-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_personalized_test_answer_personalized_test_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotInfo',
            fields=[
                ('sn', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='sn')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='date')),
                ('fandom_bot', models.IntegerField(default=0, null=True, verbose_name='fandom bot')),
                ('lucky_bot', models.IntegerField(default=0, null=True, verbose_name='fandom bot')),
                ('rpg_bot', models.IntegerField(default=0, null=True, verbose_name='fandom bot')),
            ],
            options={
                'db_table': 'bot_info',
                'managed': False,
            },
        ),
    ]
