# Generated by Django 5.0.6 on 2024-07-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_botinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotReview',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('uid', models.BigIntegerField(null=True, verbose_name='uid')),
                ('review', models.CharField(max_length=300, null=True, verbose_name='review')),
                ('star_rating', models.IntegerField(null=True, verbose_name='star_rating')),
                ('review_on', models.DateField(null=True, verbose_name='review_on')),
            ],
            options={
                'db_table': 'bot_review',
                'managed': False,
            },
        ),
    ]
